apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-was
  namespace: backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-was
  template:
    metadata:
      labels:
        app: item-was
    spec:
      containers:
      - image: 992382600671.dkr.ecr.ap-northeast-2.amazonaws.com/item-was:v1.3
        name: item-was
        ports:
        - containerPort: 8080
        env:
        - name: NODE_IP
          valueFrom: {fieldRef: {fieldPath: status.hostIP}}
        - name: NODE_NAME
          valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
        - name: POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        - name: OKIND
          value: item-was
        - name: license
          value: x604h6k85hfkr-z5n6vc0i6tdoih-z2r2bgefe66mce
        - name: whatap_server_host
          value: 13.124.11.223/13.209.172.35
        - name: whatap_micro_enabled
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 200Mi
      nodeSelector:
        web: item
---
apiVersion: v1
kind: Service
metadata:
  name: item-svc
  namespace: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: item-was
  type: ClusterIP
  clusterIP: 172.20.0.200
